name: benchmarks

on:
  workflow_dispatch:

jobs:
  deploy-runner:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: iterative/setup-cml@v1

      - name: deploy
        env:
          repo_token: ${{ secrets.HAYSTACK_BOT_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_CI_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_CI_SECRET_ACCESS_KEY }}
          AWS_CML_SECURITY_GROUP: ${{ secrets.AWS_CML_SECURITY_GROUP }}
        run: |
          cml runner launch \
          --cloud aws \
          --cloud-region eu-central-1 \
          --cloud-type=p3.2xlarge \
          --cloud-aws-security-group="$AWS_CML_SECURITY_GROUP" \
          --labels=cml

  run-benchmarks:
    needs: deploy-runner
    runs-on: [self-hosted, cml]
    container:
      image: docker://iterativeai/cml:0-dvc2-base1-gpu
      options: --gpus all
    steps:
      - uses: actions/checkout@v3

      - name: Install Haystack
        run: pip install .[metrics,elasticsearch,weaviate,opensearch,benchmarks,inference]

      - name: Run benchmarks
        run: |
          cd tests/benchmarks
          mkdir +p out
          for f in ./configs/**/*.yml; do
            echo "kill docker containers"
            docker kill "$(docker ps -q)"
            name="${f%.*}"
            echo "=== Running benchmarks for $name ===";
            config_name="$(basename "$name")"
            python run.py --output "out/$config_name.json" "$f";
            echo "=== Benchmarks done for $name (or failed) ===";
          done

      - name: Send Benchmark results to Datadog
        run: |
          python datadog/send_metrics.py
